### ISSUE TITLE
More then one day with option set to 0

### ISSUE THREAD

**Issue by dannymertens** [marksie1988/atomic_calendar_revive#44]
**Describe the bug**

Hi I set the option maxDaysToShow to 0 but still see more then one day (tomorrow) this was working fine with the original version but I like to use yours because of the extra options, can you check this please?

Thanks!

**Expected behavior**
Only show appointments of current day 

**Screenshots**

![image](https://user-images.githubusercontent.com/46963011/78424253-7cc43380-766c-11ea-80e7-b6075f3ae2ec.png)

**Setup Information (please complete the following information):**
 - Plugin Version
![image](https://user-images.githubusercontent.com/46963011/78424270-9b2a2f00-766c-11ea-9244-c356da1c8e25.png)

 - Browser & Version [e.g. chrome, safari, chrome mobile etc.]

Mac OS Google Chrome latest version, iOS latest version, Chromium Rpi

**Additional context**

```
dateColor: white
name: false
dateSize: 70
dayWrapperLineColor: white
descSize: 70
dimFinishedEvents: true
entities:
  - entity: calendar.martine
  - entity: calendar.michael
  - entity: calendar.danny
  - entity: calendar.mertens_geysen
eventBarColor: white
finishedEventFilter: grayscale(100%)
finishedEventOpacity: 0.6
fullDayEventText: Dag afspraak
hoursFormat: 24
language: nl
sortByStartTime: true
locationIconColor: 'rgb(230, 124, 115)'
locationLinkColor: white
locationTextSize: 80
maxDaysToShow: 0
maxEventCount: 0
noEventsForTodayText: Geen afspraken vandaag
progressBarColor: white
showColors: true
showCurrentEventLine: false
showDescription: true
showLoader: true
showLocation: true
showMonth: false
showNoEventsForToday: true
showProgressBar: true
timeColor: white
timeSize: 80
titleColor: white
titleSize: 90
type: 'custom:atomic-calendar-revive'
untilText: Tot
showDate: false
disableEventLink: true
```
